# DB
# mysql
# mariaDB
# percona
use_db : mysql

# MySQL Server
# mysql-5.6
# mysql-5.7
# mysql-8.0
mysql_select_server : mysql-8.0

# Maria DB
#

# Percorna Server
# 5.5
# 5.6
# 5.7
percona_select_server: 5.7